import { useEffect, useState } from "react";
import { useSearchParams, useNavigate } from "react-router-dom";
import { supabase } from "@/lib/supabase";
import { Loader2, CheckCircle2, XCircle } from "lucide-react";

/**
 * /auth/handoff?token_hash=XXX&type=magiclink
 *
 * Receives a handoff token (generated by the auth-handoff Edge Function on
 * finventree.com) and exchanges it for a full session via verifyOtp.
 * After success, redirects to the dashboard.
 *
 * Used when:
 * - User completes registration/activation on finventree.com and clicks "Open Web App"
 * - The landing site generates a handoff token and redirects here
 */
export default function AuthHandoff() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const [status, setStatus] = useState<"loading" | "success" | "error">("loading");
  const [errorMsg, setErrorMsg] = useState("");

  useEffect(() => {
    const tokenHash = searchParams.get("token_hash");
    const type = (searchParams.get("type") as "magiclink") || "magiclink";

    if (!tokenHash) {
      setStatus("error");
      setErrorMsg("Missing handoff token.");
      return;
    }

    (async () => {
      try {
        const { error } = await supabase.auth.verifyOtp({
          token_hash: tokenHash,
          type,
        });

        if (error) {
          setStatus("error");
          setErrorMsg(error.message);
          return;
        }

        // Mark local auth flag so ProtectedRoute doesn't flash
        localStorage.setItem("finventree_auth", "true");
        setStatus("success");

        // Brief delay so user sees success, then redirect
        setTimeout(() => {
          navigate("/", { replace: true });
        }, 800);
      } catch (err: any) {
        setStatus("error");
        setErrorMsg(err?.message || "Handoff failed");
      }
    })();
  }, [searchParams, navigate]);

  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-slate-50 dark:bg-slate-950 px-6">
      {status === "loading" && (
        <>
          <Loader2 className="h-10 w-10 animate-spin text-primary-500 mb-4" />
          <p className="text-sm font-medium text-slate-600 dark:text-slate-400">
            Signing you in...
          </p>
        </>
      )}
      {status === "success" && (
        <>
          <CheckCircle2 className="h-10 w-10 text-emerald-500 mb-4" />
          <p className="text-sm font-medium text-slate-900 dark:text-slate-100">
            You're in! Redirecting...
          </p>
        </>
      )}
      {status === "error" && (
        <>
          <XCircle className="h-10 w-10 text-red-500 mb-4" />
          <p className="text-sm font-medium text-red-600 dark:text-red-400 mb-2">
            Sign-in failed
          </p>
          <p className="text-xs text-slate-500 dark:text-slate-400 text-center max-w-xs">
            {errorMsg || "The link may have expired. Please try logging in again."}
          </p>
          <button
            onClick={() => navigate("/login", { replace: true })}
            className="mt-6 px-5 py-2.5 bg-primary-500 text-white text-sm font-semibold rounded-lg"
          >
            Go to Login
          </button>
        </>
      )}
    </div>
  );
}
